import os
import random
from datetime import datetime
import pytz
from slack_bolt import App

# -------------------------- CONFIG --------------------------
SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
CHANNEL_ID      = os.getenv("CHANNEL_ID")
TZ_NAME         = os.getenv("TZ", "America/New_York")

app = App(token=SLACK_BOT_TOKEN)

# --------------------- ALL YOUR 300+ SAFETY TIPS -----------------------
tips = [
    "Adjust chair height so feet are flat on the floor and knees at 90°.",
    "Keep monitor at arm's length and top of screen at eye level.",
    "Use a document holder to avoid neck strain.",
    "Take micro-breaks every 30 minutes to stretch.",
    "Position keyboard so elbows are at 90° and wrists straight.",
    "Use a wrist rest only when not typing.",
    "Stand and walk every hour if sitting for long.",
    "Use a headset for prolonged phone calls.",
    "Avoid cradling phone between ear and shoulder.",
    "Keep frequently used items within easy reach.",
    "Use lumbar support for lower back.",
    "Avoid twisting torso—turn entire body.",
    "Keep desk clutter-free to prevent strain.",
    "Use anti-glare screen filters if needed.",
    "Adjust lighting to reduce eye strain.",
    "Use footrest if feet don't reach floor.",
    "Avoid slouching—sit back fully in chair.",
    "Use ergonomic mouse to reduce wrist strain.",
    "Stand periodically using adjustable desks.",
    "Report faulty chairs or desks immediately.",
    "Don't overload power strips.",
    "Unplug devices when not in use.",
    "Inspect cords for fraying—replace if damaged.",
    "Use surge protectors, not extension cords as permanent solutions.",
    "Keep liquids away from electronics.",
    "Don't run cords under rugs or chairs.",
    "Turn off appliances at the socket when leaving.",
    "Report flickering lights or warm outlets.",
    "Avoid daisy-chaining power strips.",
    "Use grounded (3-prong) plugs properly.",
    "Keep space heaters 3 feet from flammables.",
    "Never use damaged plugs or sockets.",
    "Label circuit breakers clearly.",
    "Don't block access to electrical panels.",
    "Use GFCI outlets in break rooms/kitchens.",
    "Know locations of fire exits and extinguishers.",
    "Keep exits and pathways unobstructed.",
    "Never block sprinklers with decorations.",
    "Store flammable items in approved cabinets.",
    "Don't store items within 18” of sprinkler heads.",
    "Test smoke detectors monthly.",
    "Participate in fire drills seriously.",
    "Close doors when evacuating to contain fire.",
    "Use only approved space heaters with auto shut-off.",
    "Don't leave candles or open flames.",
    "Report burnt smells or smoke immediately.",
    "Know how to use a fire extinguisher (PASS: Pull, Aim, Squeeze, Sweep).",
    "Keep fire doors closed—not propped open.",
    "Avoid overloading trash bins with paper.",
    "Store chemicals (cleaners) away from heat.",
    "Don't store boxes in electrical rooms.",
    "Use flame-retardant decorations only.",
    "Report missing or expired extinguishers.",
    "Never use elevators during a fire.",
    "Have a designated assembly point outside.",
    "Clean spills immediately—use “Wet Floor” signs.",
    "Secure loose carpet edges with tape.",
    "Keep drawers and cabinets closed.",
    "Use step stools—never chairs—for reaching.",
    "Report loose handrails or stairs.",
    "Wear stable, closed-toe shoes.",
    "Don't run in the office.",
    "Keep walkways free of boxes and cords.",
    "Use cord covers for floor cables.",
    "Report burnt-out lights in stairwells.",
    "Avoid carrying loads that block vision.",
    "Use handrails on stairs—always.",
    "Don't stand on swivel chairs.",
    "Keep file cabinets closed and loaded bottom-up.",
    "Mark glass doors with decals.",
    "Avoid wet shoes on slick floors.",
    "Report uneven flooring or tiles.",
    "Don't leave bags in walkways.",
    "Use anti-slip mats in entryways.",
    "Keep stairwells clear of storage.",
    "Wash hands for 20 seconds frequently.",
    "Use hand sanitizer when soap isn't available.",
    "Cover coughs/sneezes with elbow.",
    "Stay home if sick with contagious illness.",
    "Clean shared keyboards/mice weekly.",
    "Open windows for ventilation if possible.",
    "Use humidifiers in dry seasons (clean regularly).",
    "Report pest sightings (ants, rodents).",
    "Avoid strong fragrances (allergy awareness).",
    "Keep personal food sealed to avoid pests.",
    "Drink water—stay hydrated.",
    "Use blue-light glasses if staring at screens 8+ hrs.",
    "Report mold or water leaks.",
    "Take stairs when possible for activity.",
    "Avoid sharing personal items (cups, phones).",
    "Get annual flu shots.",
    "Report poor air quality or strange odors.",
    "Use air purifiers in shared spaces if approved.",
    "Maintain 3-foot distance in meetings if sick.",
    "Clean high-touch surfaces (doorknobs, copiers) daily.",
    "Know evacuation routes and muster points.",
    "Keep emergency contact list updated.",
    "Have a first-aid kit in every pod/area.",
    "Train staff on AED locations and use.",
    "Conduct monthly safety huddles.",
    "Update floor wardens annually.",
    "Keep emergency flashlights charged.",
    "Store 72-hour emergency kits (water, snacks).",
    "Practice “Stop, Drop, Roll” for clothing fires.",
    "Know how to assist disabled colleagues.",
    "Report missing safety signage.",
    "Keep emergency numbers posted.",
    "Have a backup communication plan (walkie-talkies).",
    "Test PA system monthly.",
    "Review incident reports to prevent recurrence.",
    "Badge in/out—never tailgate.",
    "Report lost badges immediately.",
    "Don't share access codes.",
    "Lock desks with sensitive HR files.",
    "Shred confidential documents.",
    "Challenge unfamiliar people without badges.",
    "Keep server rooms locked and cooled.",
    "Use privacy screens on monitors.",
    "Log out of computers when away.",
    "Report suspicious packages.",
    "Use CCTV blind spot map for awareness.",
    "Escort visitors at all times.",
    "Secure laptops with cable locks.",
    "Don't discuss sensitive info in open areas.",
    "Use strong, unique passwords.",
    "Clean microwave after use.",
    "Don't leave food cooking unattended.",
    "Label personal food in fridge.",
    "Clean fridge weekly—discard old items.",
    "Use oven mitts for hot items.",
    "Store knives safely in blocks.",
    "Don't overfill coffee makers.",
    "Report leaking fridges or appliances.",
    "Use step-free paths to avoid spills.",
    "Keep floors dry—wipe spills instantly.",
    "Don't store chemicals near food.",
    "Use dishwasher-safe items only.",
    "Empty trash before it overflows.",
    "Report pest traps needing service.",
    "Use cutting boards—never countertops.",
    "Encourage use of EAP (Employee Assistance Program).",
    "Promote “no meetings” focus blocks.",
    "Train managers on burnout signs.",
    "Offer quiet rooms for decompression.",
    "Normalize mental health days.",
    "Host monthly wellness webinars.",
    "Avoid after-hours emails when possible.",
    "Celebrate small wins to boost morale.",
    "Train on conflict de-escalation.",
    "Survey staff anonymously on stress levels.",
    "Never click links in unsolicited emails.",
    "Enable two-factor authentication (2FA) on all accounts.",
    "Lock your screen when stepping away.",
    "Don't use public Wi-Fi for sensitive HR data.",
    "Update software and OS monthly.",
    "Use VPN when working remotely.",
    "Report phishing attempts to IT immediately.",
    "Avoid writing passwords on sticky notes.",
    "Use password manager for unique passwords.",
    "Don't plug unknown USB drives into work PCs.",
    "Encrypt sensitive files before emailing.",
    "Log out of shared devices after use.",
    "Avoid auto-saving passwords in browsers.",
    "Use secure file-sharing tools (not personal email).",
    "Report slow devices—may indicate malware.",
    "Don't force jammed paper—use release lever.",
    "Allow printers to cool before clearing jams.",
    "Keep toner cartridges upright to avoid spills.",
    "Recycle toner in designated bins.",
    "Report unusual noises from printers.",
    "Don't place liquids near copiers.",
    "Use paper trays—don't overstack.",
    "Clean glass platen with approved wipes only.",
    "Unplug before deep cleaning.",
    "Keep hands clear of fuser area (hot).",
    "Don't exceed weight limits on shelves.",
    "Anchor tall file cabinets to walls.",
    "Don't stack chairs for storage.",
    "Inspect desk legs for stability monthly.",
    "Replace wobbly tables immediately.",
    "Use anti-tip kits on drawers.",
    "Don't use broken chairs—even temporarily.",
    "Label heavy boxes with weight.",
    "Use team lifts for items over 50 lbs.",
    "Keep aisles 36” wide for wheelchair access.",
    "Change HVAC filters quarterly.",
    "Avoid blocking air vents with furniture.",
    "Use low-VOC office supplies.",
    "Open blinds to allow natural light.",
    "Keep plants watered to avoid mold.",
    "Report musty smells promptly.",
    "Use exhaust fans in restrooms.",
    "Avoid aerosol sprays near desks.",
    "Test CO2 levels in conference rooms.",
    "Clean ducts annually.",
    "Use noise-canceling headphones in open areas.",
    "Keep phone volumes low.",
    "Take loud calls in private rooms.",
    "Use soft-close drawers and cabinets.",
    "Avoid speakerphone in shared spaces.",
    "Install acoustic panels in meeting rooms.",
    "Schedule noisy tasks (shredding) after hours.",
    "Use rubber feet on equipment.",
    "Report rattling vents or AC units.",
    "Limit hallway conversations near desks.",
    "Separate recyclables from trash.",
    "Empty shredder bins daily.",
    "Use leak-proof bins for food waste.",
    "Don't overfill trash cans.",
    "Label bins clearly: Trash, Recycle, Compost.",
    "Dispose of batteries in e-waste bins.",
    "Flatten cardboard before recycling.",
    "Report overflowing bins immediately.",
    "Use reusable cups instead of disposable.",
    "Clean bins weekly to avoid odors.",
    "Replace burnt bulbs same day.",
    "Use LED bulbs to reduce heat.",
    "Don't use frayed or exposed lamp cords.",
    "Keep emergency lighting paths clear.",
    "Avoid dangling light fixtures.",
    "Report buzzing or humming lights.",
    "Use task lighting to reduce eye strain.",
    "Don't cover lamps with paper or cloth.",
    "Install motion-sensor lights in storage rooms.",
    "Clean light fixtures to maintain brightness.",
    "Use proper ladder when changing ceiling bulbs.",
    "Avoid loose jewelry near fans or vents.",
    "Keep long hair tied back near equipment.",
    "Don't wear open-toe shoes in storage areas.",
    "Use cut-resistant gloves when opening boxes.",
    "Avoid carrying sharp objects point-up.",
    "Store scissors and letter openers safely.",
    "Don't leave pens in shirt pockets near face.",
    "Use safety goggles when using compressed air.",
    "Keep first-aid kits stocked and accessible.",
    "Train at least 10% of staff in CPR/AED.",
    "Conduct annual bloodborne pathogen training.",
    "Keep eyewash stations clear and tested.",
    "Label all allergens in shared food areas.",
    "Post emergency eye wash/shower instructions.",
    "Have a spill kit for bodily fluids.",
    "Use biohazard bags for medical waste.",
    "Report all injuries—no matter how small.",
    "Keep walk-in closets organized and lit.",
    "Use proper signage for wet or icy entrances.",
    "Install handrails on both sides of stairs.",
    "Mark step edges with high-visibility tape.",
    "Keep outdoor walkways free of ice and debris.",
    "Use salt or de-icer in winter.",
    "Report cracked sidewalks or parking lot potholes.",
    "Ensure parking lot lighting works at night.",
    "Use reflective vests when directing traffic.",
    "Keep delivery zones clear of personal vehicles.",
    "Inspect ladders before each use.",
    "Never use the top step of a stepladder.",
    "Store ladders horizontally when not in use.",
    "Use both hands when climbing ladders.",
    "Face the ladder when going up or down.",
    "Don't overreach—move the ladder instead.",
    "Keep three points of contact on ladders.",
    "Use tool belts to keep hands free.",
    "Label all emergency shut-off switches.",
    "Know how to isolate water or gas in emergencies.",
    "Keep fire blankets in kitchen areas.",
    "Store extension cords coiled when not in use.",
    "Avoid using adapters to fit wrong plugs.",
    "Test GFCI outlets monthly.",
    "Keep electrical rooms clear of storage.",
    "Use lockout/tagout for maintenance work.",
    "Never bypass safety interlocks on machines.",
    "Report all near-miss incidents.",
    "Hold safety stand-downs after incidents.",
    "Use digital checklists for daily inspections.",
    "Rotate safety champions monthly.",
    "Post safety performance on dashboards.",
    "Reward teams with zero incidents.",
    "Include safety in all new hire onboarding.",
    "Translate safety materials for all languages.",
    "Use pictograms for low-literacy areas.",
    "Audit safety compliance quarterly.",
    "Keep safety data in a shared drive.",
    "Celebrate Safety Week with fun activities.",
    "Invite guest speakers on wellness topics.",
    "Offer standing desks on request.",
    "Provide wrist supports for all new hires.",
    "Install keyboard trays where needed.",
    "Offer annual ergonomic assessments.",
    "Track musculoskeletal complaints.",
    "Provide anti-fatigue mats for standing workers.",
    "Use adjustable monitor arms.",
    "Offer chair-fitting sessions.",
    "Keep a log of ergonomic equipment issued.",
    "Train on proper lifting techniques annually.",
    "Use dolly or cart for heavy loads.",
    "Keep floors clean and dry at all times.",
    "Use caution signs during cleaning.",
    "Schedule deep cleaning after hours.",
    "Use only approved cleaning chemicals.",
    "Ventilate areas after using strong cleaners.",
    "Wear gloves when handling trash.",
    "Empty outdoor ashtrays daily.",
    "Keep pest control logs up to date.",
    "Seal food trash to prevent insects.",
    "Use green-certified pest control methods.",
    "Keep safety data sheets (SDS) accessible.",
    "Train on chemical hazard communication.",
    "Use secondary containment for liquids.",
    "Label all secondary containers.",
    "Store incompatibles separately.",
    "Dispose of old chemicals properly.",
    "Keep spill kits near chemical storage.",
    "Wear PPE when handling unknowns.",
    "Never mix cleaning chemicals.",
    "Use fume hoods for volatile substances."
]

# --------------------- POST TIP FUNCTION -----------------------
tz = pytz.timezone(TZ_NAME)
now = datetime.now(tz)
day_name = now.strftime("%A")

tip = random.choice(tips)

message = (
    f"*Good morning, team!* Happy *{day_name}*!\n\n"
    f"Here's your *Daily Office Safety Tip*:\n\n"
    f"> {tip}\n\n"
    f"Stay safe and have a great day! :sunny:"
)

try:
    app.client.chat_postMessage(channel=CHANNEL_ID, text=message)
    print(f"Tip posted successfully on {day_name}!")
except Exception as e:
    print(f"Error posting tip: {e}")
